server:
  port: 8080

eureka:
  client:
    register-with-eureka: false

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: orders
          uri: http://localhost:8090
          predicates:
            - Path=/api/order/**
        - id: clients
          uri: http://localhost:9090
          predicates:
            - Path=/api/client/**