server:
  port: 9090

spring:
  application:
    name: msvc-client
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${url_postgresql}
    username: ${username_postgresql}
    password: ${password_postgresql}
  jpa:
    hibernate:
      ddl-auto: create
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka